# Generated by Django 5.1.3 on 2024-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_created_data_order_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='carbonhydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
