# Generated by Django 5.1.3 on 2024-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_storage_itemsinstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
